"""table slots colums ad_id nullable - True

Revision ID: 1768458044b1
Revises: 10ac4f57ed85
Create Date: 2026-06-06 15:57:25.874133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1768458044b1'
down_revision: Union[str, Sequence[str], None] = '10ac4f57ed85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slot_bookings', 'ad_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slot_bookings', 'ad_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
