"""add_pre_publication_expires_at_to_users

Revision ID: 3a5777878545
Revises: a50202872471
Create Date: 2026-06-08 22:31:25.125452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a5777878545'
down_revision: Union[str, Sequence[str], None] = 'a50202872471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pre_publication_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pre_publication_expires_at')
    # ### end Alembic commands ###
