"""add is_payment_blocked to users

Revision ID: 51c74fac4071
Revises: 892513b42b79
Create Date: 2026-07-03 13:35:44.014412

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "51c74fac4071"
down_revision: Union[str, Sequence[str], None] = "892513b42b79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_payment_blocked", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_payment_blocked")
    # ### end Alembic commands ###
