"""nullable ad_id in slot_converted

Revision ID: 563c1d00d4b1
Revises: 1768458044b1
Create Date: 2026-06-06 16:05:25.686896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '563c1d00d4b1'
down_revision: Union[str, Sequence[str], None] = '1768458044b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slot_converted', 'ad_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slot_converted', 'ad_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
