"""add notify_scheduled to publications

Revision ID: 5e1740d656ab
Revises: c2a5d1e88f30
Create Date: 2026-08-05 15:01:49.040541

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5e1740d656ab"
down_revision: Union[str, Sequence[str], None] = "c2a5d1e88f30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__ads_legacy_id"), table_name="ads")
    op.drop_column("ads", "legacy_id")
    op.add_column(
        "publications",
        sa.Column(
            "notify_scheduled", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.drop_index(op.f("ix__regions__channel_id"), table_name="regions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix__regions__channel_id"), "regions", ["channel_id"], unique=False
    )
    op.drop_column("publications", "notify_scheduled")
    op.add_column(
        "ads", sa.Column("legacy_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_index(op.f("ix__ads_legacy_id"), "ads", ["legacy_id"], unique=False)
    # ### end Alembic commands ###
