"""init

Revision ID: 892513b42b79
Revises:
Create Date: 2026-06-14 21:19:39.315548

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "892513b42b79"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=64), nullable=False),
        sa.Column("timezone", sa.VARCHAR(length=64), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_username", sa.VARCHAR(length=64), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "DISABLED", name="regionstatus"), nullable=False
        ),
        sa.Column("settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__regions")),
        sa.UniqueConstraint("channel_id", name=op.f("uq__regions__channel_id")),
    )
    op.create_table(
        "service_definitions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=128), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "AUTOPUBLISH",
                "PRIORITY_PUBLISH",
                "PIN",
                "HIGHLIGHT",
                "PRE_PUBLICATION",
                name="publicationservicetype",
            ),
            nullable=False,
        ),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "params_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__service_definitions")),
        sa.UniqueConstraint("type", name=op.f("uq__service_definitions__type")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.VARCHAR(length=64), nullable=True),
        sa.Column("full_name", sa.VARCHAR(length=128), nullable=True),
        sa.Column("phone", sa.VARCHAR(length=16), nullable=True),
        sa.Column("role", sa.Enum("USER", "ADMIN", name="userrole"), nullable=False),
        sa.Column(
            "balance",
            sa.NUMERIC(precision=12, scale=2),
            server_default="0.00",
            nullable=False,
        ),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column(
            "pre_publication_expires_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
            name=op.f("users_region_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__users")),
    )
    op.create_index(op.f("ix__users_tg_id"), "users", ["tg_id"], unique=True)
    op.create_table(
        "ads",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column(
            "ad_type",
            sa.Enum("SALE", "BUY", "URGENT_BUYOUT", "STORE", name="adtype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING_MODERATION",
                "READY",
                "SCHEDULED",
                "PUBLISHED",
                "ARCHIVED",
                name="adstatus",
            ),
            nullable=False,
        ),
        sa.Column("plate_number", sa.VARCHAR(length=16), nullable=True),
        sa.Column("city", sa.VARCHAR(length=128), nullable=True),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("username", sa.VARCHAR(length=64), nullable=True),
        sa.Column("phone", sa.VARCHAR(length=16), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("image_file_id", sa.Text(), nullable=True),
        sa.Column("shop_name", sa.String(length=128), nullable=True),
        sa.Column(
            "store_items", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
            name=op.f("ads_region_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("ads_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__ads")),
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "MANUAL_CARD",
                "CRYPTO",
                "TELEGRAM_STARS",
                "YOOKASSA",
                name="paymentmethod",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "WAITING_CONFIRMATION",
                "PAID",
                "FAILED",
                "EXPIRED",
                name="paymentstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "purpose",
            sa.Enum(
                "BALANCE_TOPUP",
                "PUBLICATION_SERVICE",
                "PRE_PUBLICATION",
                "SLOT",
                name="paymentpurpose",
            ),
            nullable=False,
        ),
        sa.Column("purpose_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("payments_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__payments")),
    )
    op.create_index(
        op.f("ix__payments_external_id"), "payments", ["external_id"], unique=True
    )
    op.create_index(op.f("ix__payments_status"), "payments", ["status"], unique=False)
    op.create_index(op.f("ix__payments_user_id"), "payments", ["user_id"], unique=False)
    op.create_table(
        "publications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ad_id", sa.Integer(), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "AWAITING_PAYMENT",
                "SCHEDULED",
                "PUBLISHING",
                "PUBLISHED",
                "FAILED",
                "CANCELED",
                "REPLACED",
                name="publicationstatus",
            ),
            nullable=False,
        ),
        sa.Column("slot_day", sa.Date(), nullable=True),
        sa.Column("slot_time", sa.Time(), nullable=True),
        sa.Column("publish_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduler_job_id", sa.String(length=128), nullable=True),
        sa.Column("channel_message_id", sa.BigInteger(), nullable=True),
        sa.Column("published_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ad_id"],
            ["ads.id"],
            name=op.f("publications_ad_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
            name=op.f("publications_region_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__publications")),
    )
    op.create_table(
        "slot_bookings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column("slot_day", sa.Date(), nullable=False),
        sa.Column("slot_time", sa.Time(), nullable=False),
        sa.Column("ad_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ad_id"],
            ["ads.id"],
            name=op.f("slot_bookings_ad_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
            name=op.f("slot_bookings_region_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("slot_bookings_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__slot_bookings")),
        sa.UniqueConstraint(
            "region_id", "slot_day", "slot_time", name="uq__slot_bookings__slot"
        ),
    )
    op.create_table(
        "slot_converted",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column("slot_day", sa.Date(), nullable=False),
        sa.Column("slot_time", sa.Time(), nullable=False),
        sa.Column("ad_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ad_id"],
            ["ads.id"],
            name=op.f("slot_converted_ad_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
            name=op.f("slot_converted_region_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("slot_converted_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__slot_converted")),
        sa.UniqueConstraint(
            "region_id", "slot_day", "slot_time", name="uq__slot_converted__slot"
        ),
    )
    op.create_table(
        "publication_services",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("publication_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "AUTOPUBLISH",
                "PRIORITY_PUBLISH",
                "PIN",
                "HIGHLIGHT",
                "PRE_PUBLICATION",
                name="publicationservicetype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "USED", "CANCELED", "EXPIRED", name="publicationservicestatus"
            ),
            nullable=False,
        ),
        sa.Column("price_paid", sa.Integer(), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publications.id"],
            name=op.f("publication_services_publication_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__publication_services")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("publication_services")
    op.drop_table("slot_converted")
    op.drop_table("slot_bookings")
    op.drop_table("publications")
    op.drop_index(op.f("ix__payments_user_id"), table_name="payments")
    op.drop_index(op.f("ix__payments_status"), table_name="payments")
    op.drop_index(op.f("ix__payments_external_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_table("ads")
    op.drop_index(op.f("ix__users_tg_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("service_definitions")
    op.drop_table("regions")
    # ### end Alembic commands ###
