"""add is_child to publications

Revision ID: ccf527993388
Revises: 51c74fac4071
Create Date: 2026-07-04 13:10:57.342613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf527993388'
down_revision: Union[str, Sequence[str], None] = '51c74fac4071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('is_child', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'is_child')
    # ### end Alembic commands ###
