"""add table payments

Revision ID: f897d86e1298
Revises: 3a5777878545
Create Date: 2026-06-08 23:02:41.373832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f897d86e1298'
down_revision: Union[str, Sequence[str], None] = '3a5777878545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('MANUAL_CARD', 'CRYPTO', 'TELEGRAM_STARS', 'YOOKASSA', name='paymentmethod'), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'WAITING_CONFIRMATION', 'PAID', 'FAILED', 'EXPIRED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('purpose', sa.Enum('BALANCE_TOPUP', 'PUBLICATION_SERVICE', 'PRE_PUBLICATION', 'SLOT', name='paymentpurpose'), nullable=False),
    sa.Column('purpose_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('payments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__payments'))
    )
    op.create_index(op.f('ix__payments_external_id'), 'payments', ['external_id'], unique=True)
    op.create_index(op.f('ix__payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix__payments_user_id'), 'payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix__payments_status'), table_name='payments')
    op.drop_index(op.f('ix__payments_external_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
