from typing import Protocol


class DraftReminderStore(Protocol):
    async def set_job_id(self, user_id: int, job_id: str, ttl_seconds: int) -> None: ...
    async def get_job_id(self, user_id: int) -> str | None: ...
    async def delete(self, user_id: int) -> None: ...
