from typing import Protocol

from src.application.dtos.user import UpdateUserDTO
from src.domain.entities.user import User
from src.domain.enums.role import UserRole


class UserRepository(Protocol):
    async def add(self, user: User) -> User: ...

    async def get_by_id(self, user_id: int) -> User | None: ...

    async def get_by_tg_id(self, tg_id: int) -> User | None: ...

    async def save(self, user: User) -> None: ...

    async def update(self, tg_id: int, data: UpdateUserDTO) -> User: ...

    async def find_with_active_pre_publication(self, region_id: int) -> list[User]: ...

    async def get_by_role(self, role: UserRole) -> list[User]: ...

    async def get_all(self) -> list[User]: ...

    async def get_all_active(self) -> list[User]: ...

    async def get_by_region(self, region_id: int) -> list[User]: ...
